# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-alpine

# Install system dependencies
RUN apk add --no-cache gcc musl-dev linux-headers

# Set working directory
WORKDIR /app

# Create data directory
RUN mkdir -p /app/data

# Copy all files
COPY . /app

# Make entrypoint script executable
RUN chmod +x /app/docker-entrypoint.sh

# Install Python dependencies
RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt \
    && pip install --no-cache-dir -e .

# Set environment variable
ENV PYTHONUNBUFFERED=1

# Set entrypoint
ENTRYPOINT ["/app/docker-entrypoint.sh"]

# Run the MCP server using stdio
CMD ["python", "-m", "auto_video_mcp.server"]
